language: python
python:
  - "3.6"
  - "3.7"
env:
  - NUMPY_VERSION=1.14.6
  - NUMPY_VERSION=1.16.6
  - NUMPY_VERSION=1.18.1
install:
  - pip install cython>=0.28
  - pip install numpy==$NUMPY_VERSION scipy matplotlib
  - if [ "$TRAVIS_BRANCH" = "master" ]; then
       pip install raysect;
    else
       pip install git+https://github.com/raysect/source@development;
    fi
  - dev/build.sh
# command to run tests
script: dev/test.sh
